INSERT INTO tb_user (NAME, EMAIL, PASSWORD, CREATED_AT, UPDATED_AT) VALUES ('Bob', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_user (NAME, EMAIL, PASSWORD, CREATED_AT, UPDATED_AT) VALUES ('Maria', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);

INSERT INTO tb_role (AUTHORITY, CREATED_AT, UPDATED_AT) VALUES ('ROLE_VISITOR', CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_role (AUTHORITY, CREATED_AT, UPDATED_AT) VALUES ('ROLE_MEMBER', CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);


INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre (NAME, CREATED_AT, UPDATED_AT) VALUES ('Ação', CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_genre (NAME, CREATED_AT, UPDATED_AT) VALUES ('Animação', CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_genre (NAME, CREATED_AT, UPDATED_AT) VALUES ('Aventura', CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_genre (NAME, CREATED_AT, UPDATED_AT) VALUES ('Comédia', CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_genre (NAME, CREATED_AT, UPDATED_AT) VALUES ('Comédia Romântica', CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_genre (NAME, CREATED_AT, UPDATED_AT) VALUES ('Esporte', CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_genre (NAME, CREATED_AT, UPDATED_AT) VALUES ('Ficção Científica', CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_genre (NAME, CREATED_AT, UPDATED_AT) VALUES ('Infantil', CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_genre (NAME, CREATED_AT, UPDATED_AT) VALUES ('Romance', CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);

-- Ação
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Agentes Vanguard.','Um contador está no alvo da organização.',2021,'https://images.app.goo.gl/K9PezxjUidorcvXz9','Um contador está no alvo da organização mercenária mais perigosa do mundo. Sua única esperança de sobrevivência é uma empresa chinesa de segurança secreta chamada Vanguard. <br> Após ser contratado pelo homem em perigo, o habilidoso líder da empresa Tang Huating (Jackie Chan) decide entrar em ação. Para isso, ele precisa se unir com as autoridades de Dubai e ser mais rápido do que os mercenários.',1, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Nova Ordem Espacial.','Em 2092, a Terra já está completamente devastada.',2021,'https://images.app.goo.gl/bLcAd2tdgUMafwKSA','Em 2092, a Terra já está completamente devastada e inabitável. Por isso, os seres humanos que conseguiram sobreviver em condições extremas agora vivem em órbita no espaço. Porém, a galáxia é um lugar de disputas e constantes perigos. <br> O jovem Tae-ho (Song Joong-Ki) faz parte da tripulação de uma nave coletora de lixo espacial. No entanto, eles descobrem que existe um robô humanóide conhecido por ser uma arma de destruição em massa. Então o grupo decide se envolver em uma arriscada missão para deter o mal.',1, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Até o Céu.','O jovem mecânico Ángel (Miguel Herrán) se apaixona por Estrella.',2021,'https://images.app.goo.gl/YSjPeXSY7XAZemXP8','O jovem mecânico Ángel (Miguel Herrán) se apaixona por Estrella (Carolina Yuste), uma mulher complicada que está envolvida com pessoas perigosas. Logo ele sai do subúrbio da Espanha e entra para o mundo do crime. <br> No entanto, ao aceitar participar de inúmeros roubos e golpes em Madri, um detetive implacável começa a persegui-lo com a promessa de colocar seu grupo atrás das grades.',1, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('O Homem de Aço.','No panteão dos super-heróis, Superman é o mais reconhecido e reverenciado personagem de todos os tempos.',2013,'https://images.app.goo.gl/Q8GHnXbBHHcRcob69','No panteão dos super-heróis, Superman é o mais reconhecido e reverenciado personagem de todos os tempos. Clark Kent/Kal-El (Henry Cavill) é um jovem jornalista que se sente diferente por ter poderes além da imaginação de qualquer ser humano. Há anos enviado de Krypton, um avançado planeta alienígena, à Terra, Clark sofre com a derradeira questão: "Por que estou aqui?" <br> Moldado pelos valores de seus pais adotivos, Martha (Diane Lane) e Jonathan Kent (Kevin Costner), Clark logo descobre que ter super-habilidades significa tomar decisões muito difíceis. Mas quando o mundo mais precisa de estabilidade, ele é atacado. E agora, suas habilidades serão usadas para manter a paz ou partir para um tudo ou nada? Clark precisa se tornar o herói conhecido como "Superman", não apenas para brilhar como a última esperança da humanidade mas para proteger aqueles que ama.',1, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);

-- Animação
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Bob Esponja.','O Incrível Resgate.',2020,'https://images.app.goo.gl/SLjtiwAHheeGFCwX8','O querido caracol de estimação de Bob Esponja (Tom Kenny) foi raptado por Poseidon e levado para a cidade perdida de Atlântida. Agora ele terá que se unir ao amigo Patrick (Bill Fagerbakke) para lutar contra o deus dos mares e trazer o amado Gary de volta.',2, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Pets Unidos!','Um terrível vilão e seu exército de robôs.',2020,'https://images.app.goo.gl/TFhS3CaUaYwYAsa28','Quando um terrível vilão e seu exército de robôs ameaçam a cidade, um cachorro decide unir uma equipe de heróis usando a sua experiência das ruas. <br> Agora ele e uma gata mimada estão no controle da segurança de todos.',2, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Nível Hard.','Um gamer adolescente.',2020,'https://images.app.goo.gl/exUmoi5Rp2WTWkAm6','Um gamer adolescente é forçado a bancar a babá quanto três bebês com superpoderes saem de seu jogo favorito e caem diretamente em seu quintal. <br> Será que ele está preparado para a missão?',2, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Scooby! - O Filme.','Scooby (Frank Welker).',2020,'https://images.app.goo.gl/TFhS3CaUaYwYAsa28','Scooby (Frank Welker) e seu grupo enfrentam um mistério ainda mais <br> desafiador: o plano de libertar um cão fantasma do mal. Para evitar o <br> apocalipse, Scooby descobre que possui um destino muito mais importante do <br> que imaginava nessa jornada. ',2, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);

-- Aventura
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Liga da Justiça.','Determinado a garantir que o sacrifício final do Superman.',2021,'https://images.app.goo.gl/CZ5AAdWimd46CK9NA','Determinado a garantir que o sacrifício final do Superman (Henry Cavill) não foi em vão, o corajoso Bruce Wayne (Ben Affleck) decide manter sua fé na humanidade, buscando a ajuda de Diana Prince (Gal Gadot) para proteger o mundo. <br> Ao recrutar uma equipe de super-heróis, Batman e Mulher-Maravilha se unem aos excêntricos Aquaman (Jason Momoa), Cyborg (Ray Fisher) e Flash (Ezra Miller). No entanto, seu plano não será nada fácil após o surgimento de um vilão catastrófico.',3, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Flora & Ulysses.','Flora (Matilda Lawler).',2021,'https://images.app.goo.gl/obARAcoMUprNzob17','Flora (Matilda Lawler) é uma garotinha que passa seu tempo lendo gibis e lutando para entender o recente divórcio dos pais. No entanto, quando seu vizinho atropela um esquilo com o aspirador de pó, a garota entra em ação para salvar o bichinho. <br> A experiência de quase-morte do esquilo fez com que ele desenvolvesse superpoderes surpreendentes. Flora ensina o novo amigo a usar seus poderes para o bem, lutando contra injustiças e ajudando quem precisa. <br> Porém, tudo desmorona quando Phyllis (Alyson Hannigan), a mãe de Flora, acha melhor que elas se livrem do animal. Magoada, a menina decide ir para a casa do pai. Mas antes que possa fazer alguma coisa, o esquilo é sequestrado.',3, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('O Grande Ivan.','O gorila Ivan.',2021,'https://images.app.goo.gl/Y2DtgkLBZA5nFceUA','O gorila Ivan vive num shopping como atração. Ele esqueceu onde viveu antes dali. Mas a chegada do filhote de elefante Ruby, Ivan quer resgatar o seu passado e juntos planejam uma fuga do shopping.',3, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Soul.','Joe (Jamie Foxx) é um professor de música.',2020,'https://images.app.goo.gl/TFhS3CaUaYwYAsa28','Joe (Jamie Foxx) é um professor de música que sonhava em ser um grande artista de jazz e tocar no lendário clube The Blue Note. Quando ele finalmente tem a chance de impressionar alguns profissionais da área durante um ensaio aberto, um terrível acidente acontece e sua alma é transportada para fora do corpo, indo parar em outra realidade. <br> No outro local, ele conhecerá outras almas que estão esperando para retornar à Terra. Com a ajuda de uma criança que ainda está aprendendo sobre si mesma, ele tentará descobrir o que precisa fazer para retomar sua vida. A sua jornada será de muitas autodescobertas, contibuindo para o seu sonho.',3, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);

-- Comédia
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Diga-me Quando.','É o primeiro trabalho de Gerardo Gatica como diretor.',2020,'https://images.app.goo.gl/xCnQfn5DVJjBydCh6','Após a morte de seu avô, o mexicano-americano Will (Jesús Zavala), que é um viciado em trabalho, decide fazer uma pausa de sua vida agitada de Los Angeles. Para se reconectar com suas raízes, ele decide realizar os últimos desejos do avô. <br> Por isso, viaja para a Cidade do México a fim de conhecer os lugares mais famosos. Mas existe outra meta mais difícil que ele também precisa atingir: se apaixonar por alguém durante a viagem.',4, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Você Já Viu Vagalumes?','Gülseren (Ecem Erkek) é uma jovem prodígio com espírito rebelde.',2021,'https://images.app.goo.gl/ARwjYqKyPmD2mw827','Gülseren (Ecem Erkek) é uma jovem prodígio com espírito rebelde e irreverente. No meio de inúmeros conflitos políticos da Turquia, ela navega entre amor, perda e solidão enquanto uma grande mudança social ocorre em seu país. Mas sua natureza sonhadora e positiva não deixará nada abalar a autoconfiança.',4, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Esquadrão Trovão.','Em um mundo onde supervilões são comuns.',2021,'https://images.app.goo.gl/p4vKJu14YPEVX46w5','Em um mundo onde supervilões são comuns, as duas melhores amigas de infância Emily (Octavia Spencer) e Lydia (Melissa McCarthy) se reúnem após anos separadas para colocar um plano em prática. <br> Emily é uma cientista brilhante que teve a ideia de fazer um tratamento que permite adquirir superpoderes. Agora a cômica dupla deseja usar suas novas forças para proteger Chicago contra o mal que está assombrando a população.',4, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Alice e o Prefeito.','O filme foi selecionado para a Quinzena dos Realizadores no Festival de Cannes 2019.',2019,'https://images.app.goo.gl/TFhS3CaUaYwYAsa28','Paul Théraneau (Fabrice Luchini) é o prefeito de Lyon, na França, e já está na política há 30 anos. No entanto, pela falta de novas ideias, sua popularidade está caindo muito, fazendo Paul enfrentar o vazio existencial de sua carreira decadente. <br> Para solucionar o problema, ele decide contratar a jovem filósofa Alice Heimann (Anaïs Demoustier). No entanto, eles tem personalidades e visões de mundo completamente distintas. Até que ponto a parceria dará certo para a cidade de Lyon?',4, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);


-- Comédia Romântica
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Solteiramente.','Dineo (Fulu Mugovhani) já está acostumada com decepções amorosas.',2020,'https://images.app.goo.gl/B99DiEje31pr4g9EA','Dineo (Fulu Mugovhani) já está acostumada com decepções amorosas, mas não consegue esquecer seu último ex-namorado. Para isso, a sua melhor amiga está determinada em ajudá-la a curtir a vida de solteira.',5, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Amor Garantido.','Para salvar o próprio escritório de advocacia.',2020,'https://images.app.goo.gl/hXcuowe5aYwyvL1v9','Para salvar o próprio escritório de advocacia, Susan (Rachael Leigh Cook) decide aceitar o caso de Nick (Damon Wayans Jr.) que quer processar um site de namoro por propaganda enganosa. No entanto, o andamento do processo acaba criando um clima entre os dois.',5, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Noite de Verão.','Jovens amigos resolvem passar o verão no mesmo lugar.',2019,'https://images.app.goo.gl/LvPTWH2fdmwzLd6CA','Jovens amigos resolvem passar o verão no mesmo lugar. No entanto, todo esse tempo juntos causará muitos conflitos e frustrações em seus relacionamentos amorosos da adolescência.',5, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Santa Girl.','A filha do Papai Noel (Jennifer Stone) sempre levou uma vida isolada.',2019,'https://images.app.goo.gl/5RcjCZSTkFULWphN7','A filha do Papai Noel (Jennifer Stone) sempre levou uma vida isolada no Pólo Norte, até que decide sair da região para cursar um semestre de faculdade no mundo normal. No entanto, perto do natal, ela precisará retornar para as tarefas da família.',5, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);

-- Esporte
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Na Mesma Onda.','Sob o sol da Sicília, na Itália, nasce uma história de amor.',2021,'https://images.app.goo.gl/C7SU5ASzcwVPUKkw7','Sob o sol da Sicília, na Itália, nasce uma história de amor entre dois jovens que passam o verão envolvidos no projeto de aproveitar as férias. No entanto, um contra-tempo faz seu romance se transformar em uma dolorosa paixão cheia de dificuldades. Agora eles precisarão amadurecer para superar a situação e seguir em frente.',6, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Sonhos Olímpicos.','A rotina de Léo (Daniel Rocha) sempre dificultou o seu sonho.',2019,'https://images.app.goo.gl/gBTxUHs7VL2jyBFK6','A rotina de Léo (Daniel Rocha) sempre dificultou o seu sonho de ser um jogador de futebol bem sucedido. No entanto, não é agora que ele vai desistir. Lembrando do ditado que o brasileiro nunca desiste, ele vai à luta em sua última grande chance.',6, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Creed II.','Adonis (Michael B. Jordan) lutou para manter escondido seu famoso sobrenome.',2018,'https://images.app.goo.gl/t2DMkqf56CCFaUQFA','Adonis (Michael B. Jordan) lutou para manter escondido seu famoso sobrenome, Creed, para provar que podia ser um boxeador. Ele se deu bem e agora, Creed tem a chance de vingar a morte do pai, Apollo. Ele vai enfrentar o filho do lutador que matou seu pai, o russo Ivan Drago (Dolph Lundgren).', 6, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Free Solo.','O documentário segue Alex Honnold.',2018,'https://images.app.goo.gl/tUMvk1UBxWfTp99U9','O documentário segue Alex Honnold e como ele se torna a primeira pessoa a escalar sozinha a parede El Capitan, de Yosemite na Califórnia. Sem cordas ou equipamentos de segurança, ele completou o maior feito na história da escalada.',6, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);

-- Ficção Científica
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Salvem-se!.','Um jovem casal do Brooklyn decide ir para uma cabana isolada descansar.',2020,'https://images.app.goo.gl/v1GUPkdp262rzVjf9','Um jovem casal do Brooklyn decide ir para uma cabana isolada descansar de tanta tecnologia. No entanto, em seu processo de reaproximação, o planeta começa a ser atacado. Agora eles precisam sobreviver vivendo no meio da natureza por conta própria.',7, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Espontâneo.','Uma pílula misteriosa que dá superpoderes imprevisíveis aos usuários.',2020,'https://images.app.goo.gl/YuWkoDeyzj3qeMqh6','Mara (Katherine Langford) e Dylan (Charlie Plummer) estão quase se formando no colegial quando um estranho fenômeno começa a aterrorizar o mundo. Os jovens estão explodindo pelos ares e a qualquer momento eles podem ser a próxima vítima aleatória. Então a dupla decide viver cada dia como se fosse o último.',7, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Power.','Adonis (Michael B. Jordan) lutou para manter escondido seu famoso sobrenome.',2018,'https://images.app.goo.gl/t2DMkqf56CCFaUQFA','Uma pílula misteriosa que dá superpoderes imprevisíveis aos usuários acaba de chegar em Nova Orleans, Estados Unidos. Agora uma traficante adolescente, um policial e um ex-soldado precisam se unir para deter a organização por trás disso.', 7, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Projeto Gemini.','Um assassino (Will Smith) está querendo se aposentar.',2019,'https://images.app.goo.gl/DJoDsJoN2etS5Xt37','Um assassino (Will Smith) está querendo se aposentar. Mas antes ele precisa enfrentar um inimigo que jamais tinha imaginado: um clone seu, 25 anos mais jovem e cheio de vitalidade e vontade de matá-lo.',7, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);

-- Infantil
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Frozen 2.','A destemida Anna já teve de enfrentar muitos desafios.',2019,'https://images.app.goo.gl/iMsrPGSgCV6A5tSo9','A destemida Anna já teve de enfrentar muitos desafios para encontrar sua irmã, Elsa, cujos poder fez o reino de Arendelle a ter um inverno eterno. Agora, as duas, na companhia no boneco de neve Olaf, vão viver aventuras ainda mais desafiadoras.',8, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Encantado.','Cinderela, Branca de Neve e Bela Adormecida.',2017,'https://images.app.goo.gl/4hNe3c1pbwjJPTG19','Cinderela, Branca de Neve e Bela Adormecida estão felizes e apaixonadas pelos seus noivos, apenas aguardando a grande cerimônia do casamento. O que as princesas não faziam ideia é que todas estão noivas do mesmo Príncipe Encantado.',8, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Os Incríveis 2.','Bob Parr já salvou o mundo na pele do Senhor Incrível.',2018,'https://images.app.goo.gl/hhs1ZwthPRvWBark8','Bob Parr já salvou o mundo na pele do Senhor Incrível, juntamente com sua família superpoderosa. Agora sua vida caiu na rotina e tem passado o tempo cuidando do bebê Zezé, enquanto a sua esposa, Helen, é quem ataca de salvadora do universo como a Mulher-Elástica.', 8, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Kung Fu Panda 3.','O desajeitado urso panda Po (dublado originalmente por Jack Black).',2016,'https://images.app.goo.gl/2wetRR2xzGsK9D5TA','O desajeitado urso panda Po (dublado originalmente por Jack Black), segue sua jornada ao lado do mestre Shifu (Dustin Hoffman), Tigresa (Angelina Jolie), Macaco (Jackie Chan), Víbora (Lucy Liu) e Louva-Deus (Seth Rogen). O grupo precisa enfrentar uma força sobrenatural e Po vai finalmente conhecer o seu pai verdadeiro, que havia sumido.',8, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);

-- Romance
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Na Batida do Coração.','Katya (Alexandra Pfeifer) é um jovem sonhadora.',2020,'https://images.app.goo.gl/1ngsCfEUeTzkCwe98','Katya (Alexandra Pfeifer) é um jovem sonhadora que treina para ser uma grande bailarina clássica. No entanto, ela acaba descobrindo o hip-hop e se apaixona pelo novo ritmo, além de conhecer Marlon (Yalany Marschner) um garoto encantador. Agora Katya precisará decidir entre seguir os planos  de seus pais ou se jogar na nova paixão artística.',9, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Tudo por Ela.','Rei Nagasawa (Kiko Mizuhara) é uma jovem mulher lésbica.',2021,'https://images.app.goo.gl/saTajXnpJ5Be5VHN7','Rei Nagasawa (Kiko Mizuhara) é uma jovem mulher lésbica que possui sentimentos pela amiga chamada Nanae (Honami Sato). No entanto, o amor platônico muda quando Rei descobre que Nanae está sofrendo violência doméstica do marido e decide matar o homem para salvá-la. <br> Depois do assassinato, as duas precisam fugir juntas para sobreviver. Nanae resiste em aceitar o crime e tem nojo de tudo que aconteceu. Já Rei sabe que agiu certo para salvar Nanae da violência. Agora as duas desfrutarão de um novo romance arrebatador, mas suas emoções sempre serão incompatíveis.',9, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Segunda-feira.','Chloe (Denise Gough) e Mickey (Sebastian Stan) se conhecem em uma sexta-feira.',2020,'https://images.app.goo.gl/ZK3cLBuXK2VMjWc38','Chloe (Denise Gough) e Mickey (Sebastian Stan) se conhecem em uma sexta-feira e logo estabelecem uma forte conexão. A faísca da nova relação os leva a uma aventura frenética de fim de semana. <br> No entanto, o que acontecerá quando chegar a inevitável segunda-feira e suas vidas voltarem ao cotidiano de sempre? Agora Chloe e Mickey precisam descobrir como continuar sua aventura romântica.', 9, CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);
INSERT INTO tb_movie (TITLE, SUB_TITLE, YEAR, IMG_URL, SYNOPSIS, GENRE_ID, CREATED_AT, UPDATED_AT) VALUES ('Chuva que Cai do Céu.','Kevin (Jefri Nichol) não soube como se declarar para a melhor amiga.', 2020 , 'https://images.app.goo.gl/zcRB7dVbLsbtzGiXA', 'Kevin (Jefri Nichol) não soube como se declarar para a melhor amiga Nara (Aurora Ribero) e agora ela está apaixonada por outro cara. Sem esperança de conquistá-la, o jovem sente que é melhor desistir desse romance. No entanto, o destino ainda surpreenderá os dois com o inesperado.' , 9 , CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE, null);







